import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout.jsx";
import { api } from "../api.js";

export default function BusinessRequestsPage({ user, onLogout }) {
  const [items,setItems]=useState([]),[error,setError]=useState("");
  useEffect(()=>{api.admin.businessRequests().then(setItems).catch(e=>setError(e.message));},[]);
  async function review(id,status){const reason=status==="rejected"?window.prompt("Reason for rejection:")?.trim():"";if(status==="rejected"&&!reason)return;try{const updated=await api.admin.reviewBusiness(id,{status,rejectionReason:reason});setItems(current=>current.map(item=>item._id===id?updated:item));}catch(e){setError(e.message);}}
  return <AppLayout user={user} onLogout={onLogout}><header className="topbar"><div><p className="eyebrow">ADMIN REVIEW</p><h1>Business requests</h1><p className="muted">Approve, reject, or suspend business profiles.</p></div></header>{error&&<p className="error">{error}</p>}<section className="request-list">{items.length===0?<div className="panel"><p className="muted">No business applications yet.</p></div>:items.map(item=><article className="panel" key={item._id}><div className="panel-title"><div><h2>{item.name}</h2><p className="muted">{item.category} · {item.location}</p></div><span className={`status ${item.status}`}>{item.status}</span></div><p>{item.description}</p><p className="muted">Owner: {item.owner?.name} ({item.owner?.email})<br/>Business contact: {item.email} · {item.phone}</p>{item.website&&<a href={item.website} target="_blank" rel="noreferrer">Visit website</a>}{item.rejectionReason&&<p className="error">Previous feedback: {item.rejectionReason}</p>}<div className="row-actions"><button className="primary-button" onClick={()=>review(item._id,"approved")}>Approve</button><button className="danger" onClick={()=>review(item._id,"rejected")}>Reject</button>{item.status==="approved"&&<button className="secondary" onClick={()=>review(item._id,"suspended")}>Suspend</button>}</div></article>)}</section></AppLayout>;
}
