import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api.js";
import ContentCard from "../components/ContentCard.jsx";
import ProfileAvatar from "../components/ProfileAvatar.jsx";

export default function ServiceDiscoveryPage({user}) {
  const [query,setQuery]=useState(""),[category,setCategory]=useState(""),[minRating,setMinRating]=useState("0"),[tab,setTab]=useState("services"),[data,setData]=useState({users:[],services:[],hasMore:false}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[page,setPage]=useState(1);
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);setError("");api.search({q:query,category,minRating,page:1}).then(result=>{setData(result);setPage(1);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},300);return()=>clearTimeout(timer);},[query,category,minRating]);
  async function more(){setLoading(true);try{const next=page+1,result=await api.search({q:query,category,minRating,page:next});setData(current=>({users:[...current.users,...result.users],services:[...current.services,...result.services],hasMore:result.hasMore}));setPage(next);}catch(e){setError(e.message);}finally{setLoading(false);}}
  return <main className="public-page"><header className="public-top browse-top"><Link className="brand-row" to="/discover"><span className="brand-mark small">B</span><strong>BookFlow</strong></Link><div>{user?<Link className="primary-button button-link" to="/dashboard">Dashboard</Link>:<Link className="primary-button button-link" to="/login">Sign in</Link>}</div></header><section className="public-content-section browse-section"><div className="section-heading"><div><p className="eyebrow">DISCOVER</p><h1>Find users and services</h1><p className="muted">Search BookFlow providers and their public services.</p></div></div><div className="panel search-panel"><input type="search" placeholder="Search users, providers, services..." value={query} onChange={e=>setQuery(e.target.value)}/><input placeholder="Category" value={category} onChange={e=>setCategory(e.target.value)}/><select value={minRating} onChange={e=>setMinRating(e.target.value)}><option value="0">Any rating</option><option value="3">3+ stars</option><option value="4">4+ stars</option><option value="5">5 stars</option></select></div><div className="discovery-tabs"><button className={tab==="services"?"active":""} onClick={()=>setTab("services")}>Services ({data.services.length})</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Users ({data.users.length})</button></div>{error&&<p className="error">{error}</p>}{loading&&page===1?<div className="panel empty-state"><p>Searching...</p></div>:<>{tab==="services"?<div className="content-grid">{data.services.map(item=><Link key={item._id} to={`/services/${item._id}`} className="content-card-link"><ContentCard item={item}/></Link>)}{!data.services.length&&<p className="muted">No public services found.</p>}</div>:<div className="user-results">{data.users.map(profile=><Link className="panel user-result" to={`/profile/${profile.username}`} key={profile._id}><ProfileAvatar profile={profile} size="lg"/><div><h2>{profile.name}</h2><strong>@{profile.username}</strong>{profile.headline&&<p>{profile.headline}</p>}{profile.location&&<small>{profile.location}</small>}</div></Link>)}{!data.users.length&&<p className="muted">No users found.</p>}</div>}{data.hasMore&&<button className="secondary load-more" disabled={loading} onClick={more}>{loading?"Loading...":"Load more"}</button>}</>}</section></main>;
}
