import { useMemo, useState } from "react";
import ProfileAvatar from "./ProfileAvatar.jsx";
import { Link } from "react-router-dom";
import EmojiReactions from "./EmojiReactions.jsx";

export default function CommentSection({comments,currentUser,ownerId,onAdd,onEdit,onDelete,onReact,onSignIn}) {
  const [text,setText]=useState(""),[replying,setReplying]=useState(null),[replyText,setReplyText]=useState(""),[editing,setEditing]=useState(null),[editText,setEditText]=useState(""),[collapsed,setCollapsed]=useState(new Set());
  const tree=useMemo(()=>{const map=new Map(comments.map(c=>[c._id,{...c,replies:[]}])),roots=[];for(const c of map.values()){const parent=c.parent?map.get(String(c.parent)):null;(parent?parent.replies:roots).push(c);}return roots;},[comments]);
  async function submit(e){e.preventDefault();if(!text.trim())return;await onAdd(text,null);setText("");}
  async function reply(id){if(!replyText.trim())return;await onAdd(replyText,id);setReplying(null);setReplyText("");}
  async function saveEdit(id){if(!editText.trim())return;await onEdit(id,editText);setEditing(null);}
  function toggle(id){setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});}
  function node(c){const mine=String(c.user?._id)===String(currentUser?.id),moderator=String(ownerId)===String(currentUser?.id);return <article className="comment-thread" key={c._id}><div className="comment-item">{c.user?.username?<Link to={`/profile/${c.user.username}`}><ProfileAvatar profile={c.user}/></Link>:<ProfileAvatar profile={c.user}/>}<div className="comment-body"><div className="comment-head"><div><strong>{c.user?.username?<Link className="entity-link" to={`/profile/${c.user.username}`}>{c.user.name}</Link>:(c.user?.name||"User")}</strong><small>{new Date(c.createdAt).toLocaleString()}{c.edited?" · edited":""}</small></div>{currentUser&&<div className="row-actions">{!c.deletedAt&&c.depth<3&&<button className="secondary" onClick={()=>setReplying(c._id)}>Reply</button>}{mine&&!c.deletedAt&&<button className="secondary" onClick={()=>{setEditing(c._id);setEditText(c.comment);}}>Edit</button>}{(mine||moderator)&&!c.deletedAt&&<button className="danger" onClick={()=>onDelete(c._id)}>Delete</button>}</div>}</div>{editing===c._id?<div className="comment-edit"><textarea rows="3" value={editText} onChange={e=>setEditText(e.target.value)}/><div className="row-actions"><button className="primary-button" onClick={()=>saveEdit(c._id)}>Save</button><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button></div></div>:<p className={c.deletedAt?"muted":""}>{c.comment}</p>}{!c.deletedAt&&<EmojiReactions reactions={c.emojiReactions} canReact={Boolean(currentUser)} onToggle={emoji=>onReact(c._id,emoji)} label="comment"/>}{replying===c._id&&<div className="comment-edit"><textarea rows="2" placeholder="Write a reply..." value={replyText} onChange={e=>setReplyText(e.target.value)}/><div className="row-actions"><button className="primary-button" onClick={()=>reply(c._id)}>Reply</button><button className="secondary" onClick={()=>setReplying(null)}>Cancel</button></div></div>}</div></div>{c.replies.length>0&&<><button className="thread-toggle" onClick={()=>toggle(c._id)}>{collapsed.has(c._id)?`Show ${c.replies.length} replies`:`Hide ${c.replies.length} replies`}</button>{!collapsed.has(c._id)&&<div className="comment-replies">{c.replies.map(node)}</div>}</>}</article>;}
  return <section className="comments-section"><div className="section-heading"><div><p className="eyebrow">DISCUSSION</p><h2>Threaded comments</h2></div></div>{currentUser?<form className="comment-form" onSubmit={submit}><textarea rows="3" maxLength="2000" placeholder="Share your thoughts..." value={text} onChange={e=>setText(e.target.value)} required/><button className="primary-button">Post comment</button></form>:<div className="signin-callout">Want to join the discussion? <button className="link-button" onClick={onSignIn}>Sign in to continue</button></div>}<div className="comment-list">{tree.length===0?<p className="muted">No comments yet.</p>:tree.map(node)}</div></section>;
}
